/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Fases;

import java.text.Normalizer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author lab
 */
public class Fase1 extends javax.swing.JFrame {

    boolean Valendo;
    /**
     * Creates new form Fase1
     */
    public Fase1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblParede1 = new javax.swing.JLabel();
        LblParede2 = new javax.swing.JLabel();
        LblPontoFinal = new javax.swing.JLabel();
        LblInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblParede1.setBackground(new java.awt.Color(0, 0, 0));
        lblParede1.setText(".");
        lblParede1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblParede1MouseEntered(evt);
            }
        });
        lblParede1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblParede1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        LblParede2.setBackground(new java.awt.Color(0, 0, 0));
        LblParede2.setText(".");
        LblParede2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblParede2MouseEntered(evt);
            }
        });
        LblParede2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                LblParede2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        LblPontoFinal.setText(".");
        LblPontoFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblPontoFinalMouseEntered(evt);
            }
        });
        LblPontoFinal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                LblPontoFinalAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        LblInicio.setText(".");
        LblInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LblInicioMousePressed(evt);
            }
        });
        LblInicio.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                LblInicioAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblParede2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                .addComponent(LblPontoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addComponent(lblParede1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblParede1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPontoFinal)
                    .addComponent(LblInicio))
                .addGap(5, 5, 5)
                .addComponent(LblParede2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblParede1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblParede1AncestorAdded
     ImageIcon icon = new ImageIcon("src/Imagens/Preto.jpg");
        //JOptionPane.showMessageDialog(null,"src/Imagens/Carta" + rand1 + ".jpg" );
        icon.setImage(icon.getImage().getScaledInstance(lblParede1.getWidth(), lblParede1.getWidth(), 1));
        lblParede1.setIcon(icon);
    }//GEN-LAST:event_lblParede1AncestorAdded

    private void LblParede2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_LblParede2AncestorAdded
          ImageIcon icon = new ImageIcon("src/Imagens/Preto.jpg");
        //JOptionPane.showMessageDialog(null,"src/Imagens/Carta" + rand1 + ".jpg" );
        icon.setImage(icon.getImage().getScaledInstance(LblParede2.getWidth(), LblParede2.getWidth(), 1));
        LblParede2.setIcon(icon);
        
        
        
    }//GEN-LAST:event_LblParede2AncestorAdded

    private void LblPontoFinalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_LblPontoFinalAncestorAdded
        ImageIcon icon = new ImageIcon("src/Imagens/PontoFinal.jpg");
        //JOptionPane.showMessageDialog(null,"src/Imagens/Carta" + rand1 + ".jpg" );
        icon.setImage(icon.getImage().getScaledInstance(LblPontoFinal.getWidth(), LblPontoFinal.getWidth(), 1));
        LblPontoFinal.setIcon(icon);
    }//GEN-LAST:event_LblPontoFinalAncestorAdded

    private void LblInicioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_LblInicioAncestorAdded
          ImageIcon icon = new ImageIcon("src/Imagens/PontoInicial.jpg");
        //JOptionPane.showMessageDialog(null,"src/Imagens/Carta" + rand1 + ".jpg" );
        icon.setImage(icon.getImage().getScaledInstance(LblInicio.getWidth(), LblInicio.getWidth(), 1));
        LblInicio.setIcon(icon);
    }//GEN-LAST:event_LblInicioAncestorAdded

    private void LblInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInicioMousePressed
        Valendo = true;
        LblInicio.enable(false);
        
    }//GEN-LAST:event_LblInicioMousePressed

    private void lblParede1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblParede1MouseEntered
     if (Valendo){
         JOptionPane.showMessageDialog(null,"Voce Perdeu");
         Valendo = false;
     }
    }//GEN-LAST:event_lblParede1MouseEntered

    private void LblParede2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblParede2MouseEntered
        if (Valendo){
         JOptionPane.showMessageDialog(null,"Voce Perdeu");
         Valendo = false;
        }
    }//GEN-LAST:event_LblParede2MouseEntered

    private void LblPontoFinalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPontoFinalMouseEntered
          if (Valendo){
         JOptionPane.showMessageDialog(null,"Voce Ganhou");
         Valendo = false;
            new Fase2().setVisible(true);
                    this.dispose();
          }
        
          
    }//GEN-LAST:event_LblPontoFinalMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fase1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblInicio;
    private javax.swing.JLabel LblParede2;
    private javax.swing.JLabel LblPontoFinal;
    private javax.swing.JLabel lblParede1;
    // End of variables declaration//GEN-END:variables
}
